apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DevPro
  annotations:
    github.com/project-slug: itisaby/DevPro
    github.com/project-readme-path: README.md
spec:
  type: other
  lifecycle: unknown
  owner: guests
