apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DevPro
  links:
    - url: https://github.com/itisaby
      title: My Dashboard
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/itisaby/DevPro/tree/master
    github.com/project-slug: itisaby/DevPro
    github.com/project-readme-path: README.md
spec:
  type: other
  lifecycle: unknown
  owner: guests
